name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: bellsoft/liberica-runtime-container:jdk-23-musl

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'liberica'
#          java-version: '23'
#          cache: 'gradle'

      - name: Build project
        run: ./gradlew jlink --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build -t ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest .

      - name: List Docker images
        run: docker images
      
      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest
