name: Build

on:
  push:
    branches:
      - main

jobs:
  build-java-image:
    runs-on: ubuntu-latest
    container: bellsoft/liberica-runtime-container:jdk-all-23-musl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build java project
        run: ./gradlew jlink --no-daemon

      - name: Upload java image
        uses: actions/upload-artifact@v4
        with:
          name: java-image
          path: ./build/image

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-java-image
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Download java image
        uses: actions/download-artifact@v4
        with:
          name: java-image
          path: ./build

      - name: Build Docker image
        run: docker build -t ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List Docker images
        run: docker images
      
      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest
